import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load local fonts with variable font support
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Hunting Coder",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className={"bg-gray-600 text-white"}>
        <ul className={"flex justify-center gap-4 p-4 font-bold text-lg"}>
          <li className={"cursor-pointer"}>Home</li>
          <li className={"cursor-pointer"}>About</li>
          <li className={"cursor-pointer"}>Blogs</li>
          <li className={"cursor-pointer"}>Contact</li>
        </ul>
       </nav>
        {children}
      </body>
    </html>
  );
}

